export { default as capitalizeFirstLetter } from './capatilize'
export { default as getBackgroundColors } from './getBackgroundColors'
export { default as PokemonTypeColor } from './colors'
export { default as getStats } from './getStats'
export { normalizePokemon, normalizePokemonLite } from './normalizePokemon'
export { default as formatTitle } from './formatTitle'
export { default as fetcher } from './fetcher'
export { default as getPokemon } from './getPokemon'
export { default as rangeMap } from './range-map'
export { default as toPixels } from './to-pixels'
